import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      username: 'Bucko',
      email: 'bucbuc@gmail.com',
      password: bcrypt.hashSync('bucbuc'),
      role: 'user',
    },
    {
      username: 'Ante',
      email: 'antemelvan123@gmail.com',
      password: bcrypt.hashSync('12345'),
      role: 'admin',
    },
  ],
  objects: [
    {
      name: 'Gricko',
      slug: 'gricko',
      rating: 4.9,
      reviews: 100,
      status: 'otvoren',
      workTime: {
        Ponedjeljak: '09:00 - 23:00',
        Utorak: '09:00 - 23:00',
        Srijeda: '09:00 - 23:00',
        Cetvrtak: '09:00 - 23:00',
        Petak: '09:00 - 23:00',
        Subota: '09:00 - 23:00',
        Nedjelja: '12:00 - 22:00',
      },
      lokacija: 'Kastela',
      image: '/images/gricko.jpg',
      minDostava: 70,
      cijenaDostave: 1,
      products: [
        {
          _id: '1',
          name: 'Miješana pizza',
          kategorija: 'Pizze',
          productImage:
            'https://images.unsplash.com/photo-1628840042765-356cda07504e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTh8fHxlbnwwfHx8fA%3D%3D&w=1000&q=80',
          availableSizes: ['mala', 'velika', 'jumbo'],
          availableToppings: ['majoneza', 'kečap'],
          prices: [4, 6, 8],
          size: '',
          toppings: [],
          price: 0,
          slug: 'jumboPizza',
        },
        {
          _id: '2',
          name: 'Topli šunka-sir',
          kategorija: 'Sandwich',
          productImage:
            'https://imageproxy.wolt.com/menu/menu-images/622f1df92b81b9058994dff6/dd8eb2c6-b143-11ec-8fc5-86292c0db08b_mapet_product_1.jpeg',
          availableSizes: ['mali', 'veliki', 'jumbo'],
          availableToppings: [
            'majoneza',
            'kečap',
            'jaja',
            'salata',
            'kupus',
            'krastavci',
          ],
          prices: [2, 3, 4],
          size: '',
          toppings: [],
          price: 0,
          slug: 'sandwich',
        },
        {
          _id: '3',
          name: 'Ćevapi',
          kategorija: 'Meso',
          productImage:
            'https://www.croatiaweek.com/wp-content/uploads/2017/02/Plac1.png',
          availableSizes: ['5 komada', '7 komada', '10 komada'],
          availableToppings: [
            'ajvar',
            'kajmak',
            'majoneza',
            'kečap',
            'jaja',
            'salata',
            'kupus',
            'krastavci',
          ],
          prices: [4, 5, 6],
          size: '',
          toppings: [],
          price: 0,
          slug: 'cevapi',
        },
        {
          _id: '4',
          name: 'Kebab',
          kategorija: 'Meso',
          productImage:
            'https://zdravljeplus.ba/wp-content/uploads/2019/05/Slimming-World-Chicken-Doner-Kebab-Fakeaway.jpg',
          availableSizes: ['mali', 'veliki'],
          availableToppings: [
            'majoneza',
            'kečap',
            'jaja',
            'salata',
            'kupus',
            'krastavci',
          ],
          prices: [4, 5],
          size: '',
          toppings: [],
          price: 0,
          slug: 'kebab',
        },
      ],
    },
    {
      name: 'Medeni',
      slug: 'medeni',
      rating: 1,
      reviews: 77,
      status: 'otvoren',
      lokacija: 'Kastela',
      image: '/images/medeni.png',
      minDostava: 60,
      cijenaDostave: 0,
      workTime: {
        Ponedjeljak: '19:00 - 23:00',
        Utorak: '19:00 - 23:00',
        Srijeda: '19:00 - 23:00',
        Cetvrtak: '19:00 - 23:00',
        Petak: '19:00 - 23:00',
        Subota: '19:00 - 23:00',
        Nedjelja: '16:00 - 22:00',
      },
    },
    {
      name: 'Lozo',
      slug: 'lozo',
      rating: 4.0,
      reviews: 157,
      status: 'otvoren',
      lokacija: 'Split',
      image: '/images/lozo.png',
      minDostava: 75,
      cijenaDostave: 0,
      workTime: {
        Ponedjeljak: '09:00 - 23:00',
        Utorak: '09:00 - 23:00',
        Srijeda: '09:00 - 23:00',
        Cetvrtak: '09:00 - 23:00',
        Petak: '09:00 - 23:00',
        Subota: '09:00 - 23:00',
        Nedjelja: '12:00 - 22:00',
      },
      status: 'otvoren',
    },
    {
      name: 'Big mamma',
      slug: 'bigmamma',
      rating: 3.8,
      reviews: 69,
      status: 'zatvoren',
      lokacija: 'Trogir',
      image: '/images/bigmamma.png',
      minDostava: 65,
      cijenaDostave: 0,
      workTime: {
        Ponedjeljak: '09:00 - 23:00',
        Utorak: '09:00 - 23:00',
        Srijeda: '09:00 - 23:00',
        Cetvrtak: '09:00 - 23:00',
        Petak: '09:00 - 23:00',
        Subota: '09:00 - 23:00',
        Nedjelja: '12:00 - 22:00',
      },
      status: 'zatvoren',
    },
    {
      name: 'Super Pajo',
      slug: 'superpajo',
      rating: 4.8,
      reviews: 89,
      status: 'otvoren',
      lokacija: 'Solin',
      image: '/images/superpajo.png',
      minDostava: 50,
      cijenaDostave: 1,
      workTime: {
        Ponedjeljak: '09:00 - 23:00',
        Utorak: '09:00 - 23:00',
        Srijeda: '09:00 - 23:00',
        Cetvrtak: '09:00 - 23:00',
        Petak: '09:00 - 23:00',
        Subota: '09:00 - 23:00',
        Nedjelja: '12:00 - 22:00',
      },
      status: 'otvoren',
    },
  ],
};
export default data;
